/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

import edu.ijse.controller.BookController;
import edu.ijse.controller.BorrowController;
import edu.ijse.controller.MemberController;
import edu.ijse.dto.BookDto;
import edu.ijse.dto.BorrowDetailDto;
import edu.ijse.dto.BorrowDto;
import edu.ijse.dto.MemberDto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class BorrowView extends javax.swing.JFrame {
    
    private MemberController memberController;
    private BookController bookController;
    private BorrowController borrowController;
    private ArrayList<BorrowDetailDto> borrowDetailDtos=new ArrayList<>();
    

    /**
     * Creates new form BorrowView
     */
    public BorrowView() {
        this.memberController=new MemberController();
        this.bookController=new BookController();
        this.borrowController=new BorrowController();
        initComponents();
        loadTable();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        btnSearch2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBorrow = new javax.swing.JTable();
        btnRecode = new javax.swing.JButton();
        txtQty = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtMemID = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblMember = new javax.swing.JLabel();
        lblBook = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Borrow ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(71, 101, 126, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Borrow Details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(620, 10, 360, 100);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Book Code");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(71, 212, 126, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText(" Book QTY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(71, 266, 126, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Member ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(71, 152, 126, 25);

        btnSearch1.setBackground(new java.awt.Color(255, 255, 204));
        btnSearch1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch1.setText("search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch1);
        btnSearch1.setBounds(506, 149, 90, 40);

        btnSearch2.setBackground(new java.awt.Color(255, 255, 204));
        btnSearch2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch2.setText("search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch2);
        btnSearch2.setBounds(506, 206, 90, 40);

        tblBorrow.setBackground(new java.awt.Color(255, 255, 204));
        tblBorrow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBorrow);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(202, 373, 452, 365);

        btnRecode.setBackground(new java.awt.Color(255, 255, 204));
        btnRecode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRecode.setText("Record");
        btnRecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecode);
        btnRecode.setBounds(50, 680, 100, 50);

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtQty);
        txtQty.setBounds(215, 263, 242, 31);

        txtCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtCode);
        txtCode.setBounds(215, 209, 242, 31);

        txtMemID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtMemID);
        txtMemID.setBounds(215, 149, 242, 31);

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtID);
        txtID.setBounds(215, 98, 242, 31);

        lblMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblMember);
        lblMember.setBounds(609, 149, 294, 40);

        lblBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblBook);
        lblBook.setBounds(609, 200, 294, 50);

        btnAdd.setBackground(new java.awt.Color(255, 255, 204));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(500, 300, 100, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1230, 610, 100, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/wallpaperflare.com_wallpaper (3).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1870, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        searchMember();
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        searchBook();
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       addToTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecodeActionPerformed
       record();
    }//GEN-LAST:event_btnRecodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new HomeView().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BorrowView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRecode;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBook;
    private javax.swing.JLabel lblMember;
    private javax.swing.JTable tblBorrow;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMemID;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables


    private void searchMember(){
        try{
            String memID=txtMemID.getText();
            MemberDto memberDto=memberController.get(memID);
            if(memberDto!=null){
                lblMember.setText(memberDto.getMemID() + " | " + memberDto.getTitle() +  "  : " + memberDto.getMemName());
                
            }else{
               lblMember.setText("Member not found");
            }
            
        }catch(Exception e){
             e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void searchBook(){
          try{
              String bookCode=txtCode.getText();
              BookDto bookDto=bookController.get(bookCode);
              if(bookDto!=null){
                  lblBook.setText(bookDto.getBkCode() + " | " + bookDto.getBkDep());
                  
              }else{
                  lblBook.setText("Book not found");
              }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void addToTable(){
        BorrowDetailDto borrowDetailDto=new BorrowDetailDto();
        borrowDetailDto.setBkCode(txtCode.getText());
        borrowDetailDto.setQty(Integer.parseInt(txtQty.getText()));
        
        borrowDetailDtos.add(borrowDetailDto);
        
        Object[] rowData={borrowDetailDto.getBkCode(),borrowDetailDto.getQty()};
        DefaultTableModel dtm=(DefaultTableModel)tblBorrow.getModel();
        dtm.addRow(rowData);
        
        clear();
    }
    
    private void clear(){
       txtCode.setText("");
       txtQty.setText("");
       lblBook.setText("");
    }
    
    private void loadTable(){
        String columns[]={"Book Code","Qty"};
        DefaultTableModel dtm =new DefaultTableModel(columns,0){
          public boolean  isCellEditable(int row,int column){
              return false;
          }  
        };
        tblBorrow.setModel(dtm);
    }
    
    private void record(){
        try{
            BorrowDto borrowDto=new BorrowDto();
            borrowDto.setMemId(txtMemID.getText());
            borrowDto.setBorrowId(txtID.getText());
            
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(new Date());
            borrowDto.setDate(date);
            
            borrowDto.setBorrowDetailDtos(borrowDetailDtos);
            
        SimpleDateFormat sdfDue = new SimpleDateFormat("yyyy-MM-dd");
        
        // Get the current date
        Date currentDate = new Date();
        
        // Create a Calendar instance and set the current date
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currentDate);
        
        // Add 12 days to the current date
        calendar.add(Calendar.DAY_OF_MONTH, 12);
        
        // Get the new date after adding 12 days
        Date newDate = calendar.getTime();
        
        // Format the new date to a string
        String dueDate = sdfDue.format(newDate);
        
        // Assuming borrowDto is an instance of your DTO class
        borrowDto.setDueDate(dueDate);

            
            String resp=borrowController.record(borrowDto);
            JOptionPane.showMessageDialog(this,resp);
            
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

}
