/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

import edu.ijse.controller.BookController;
import edu.ijse.controller.BorrowController;
import edu.ijse.controller.MemberController;
import edu.ijse.controller.ReturnController;
import edu.ijse.dto.BookDto;
import edu.ijse.dto.BorrowDto;
import edu.ijse.dto.MemberDto;
import edu.ijse.dto.ReturnDetailDto;
import edu.ijse.dto.ReturnDto;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

    
/**
 *
 * @author User
 */
public class ReturnView extends javax.swing.JFrame {
    
    private MemberController memberController;
    private BookController bookController;
    private BorrowController borrowController;
    private ReturnController returnController;
    private ArrayList<ReturnDetailDto> returnDetailDtos=new ArrayList<>();
    


    /**
     * Creates new form ReturnView
     */
    public ReturnView() {
        this.memberController=new MemberController();
        this.bookController=new BookController();
        this.borrowController=new BorrowController();
        this.returnController=new ReturnController();
        initComponents();
        loadTable();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch1 = new javax.swing.JButton();
        btnSearch2 = new javax.swing.JButton();
        btnSearch3 = new javax.swing.JButton();
        txtReID = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtMemID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblBook = new javax.swing.JLabel();
        lblReturn = new javax.swing.JLabel();
        lblMember = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtFine = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReturn = new javax.swing.JTable();
        btnRecord = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnSearch1.setBackground(new java.awt.Color(255, 255, 204));
        btnSearch1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch1.setText("search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch1);
        btnSearch1.setBounds(1113, 129, 80, 30);

        btnSearch2.setBackground(new java.awt.Color(255, 255, 204));
        btnSearch2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch2.setText("search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch2);
        btnSearch2.setBounds(1113, 181, 80, 30);

        btnSearch3.setBackground(new java.awt.Color(255, 255, 204));
        btnSearch3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch3.setText("search");
        btnSearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch3);
        btnSearch3.setBounds(1113, 230, 80, 30);

        txtReID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtReID);
        txtReID.setBounds(715, 237, 270, 31);

        txtCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtCode);
        txtCode.setBounds(715, 181, 270, 31);

        txtMemID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtMemID);
        txtMemID.setBounds(715, 129, 270, 31);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 132, 116, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Borrow ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 237, 116, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Book Code");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(27, 184, 116, 25);

        lblBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblBook);
        lblBook.setBounds(1313, 129, 211, 40);

        lblReturn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblReturn);
        lblReturn.setBounds(1313, 227, 211, 40);

        lblMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblMember);
        lblMember.setBounds(1313, 181, 211, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Qty");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(27, 337, 116, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Return ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(27, 92, 116, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Fine");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(27, 288, 116, 25);

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtQty);
        txtQty.setBounds(715, 334, 270, 31);

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtID);
        txtID.setBounds(715, 86, 270, 31);

        txtFine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtFine);
        txtFine.setBounds(715, 285, 270, 31);

        btnAdd.setBackground(new java.awt.Color(255, 255, 204));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(1113, 324, 80, 40);

        tblReturn.setBackground(new java.awt.Color(255, 255, 204));
        tblReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReturn);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(232, 383, 630, 370);

        btnRecord.setBackground(new java.awt.Color(255, 255, 204));
        btnRecord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRecord.setText("Record");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecord);
        btnRecord.setBounds(71, 654, 100, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Return Details");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(670, 10, 340, 64);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setText("(When book is returned after the dudate , then fine is calculated else show the fine as 0.00)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 290, 490, 16);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Rs.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(680, 290, 30, 25);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1240, 600, 90, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/view/wallpaperflare.com_wallpaper (3).jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1620, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
       searchMember();
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
       searchBook();
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void txtMemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemIDActionPerformed

    private void btnSearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch3ActionPerformed
        searchBorrow();
    }//GEN-LAST:event_btnSearch3ActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
       record();
    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addToTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       setVisible(false);
       new HomeView().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReturnView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnSearch3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBook;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JTable tblReturn;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMemID;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReID;
    // End of variables declaration//GEN-END:variables



     private void searchMember(){
        try{
            String memID=txtMemID.getText();
            MemberDto memberDto=memberController.get(memID);
            if(memberDto!=null){
                lblBook.setText(memberDto.getMemID() + " | " + memberDto.getTitle() +  "  : " + memberDto.getMemName());
                
            }else{
               lblBook.setText("Member not found");
            }
            
        }catch(Exception e){
             e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void searchBook(){
          try{
              String bookCode=txtCode.getText();
              BookDto bookDto=bookController.get(bookCode);
              if(bookDto!=null){
                  lblMember.setText(bookDto.getBkCode() + " | " + bookDto.getBkDep());
                  
              }else{
                  lblMember.setText("Book not found");
              }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
     private void searchBorrow(){
        try{
              String boCode=txtReID.getText();
              String bo=borrowController.getr(boCode);
              if(bo!=null){
                  lblReturn.setText(bo);
                  
                                     
            // Get the return date from the label
    String returnDateString = lblReturn.getText();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    LocalDate returnDate = LocalDate.parse(returnDateString, formatter);

    // Get the current date
    LocalDate currentDate = LocalDate.now();

    // Calculate the difference in days
    long daysBetween = ChronoUnit.DAYS.between(returnDate, currentDate);

    // Calculate the fine
    double fine ;
    if(daysBetween<=0){
        fine=0;
    }else{
         fine = daysBetween * 5;
    }
   
    
                txtFine.setText(String.valueOf(fine));
                  
              }else{
                  lblReturn.setText("Book not found");
              }
             
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
     
     
     
      private void addToTable(){
        ReturnDetailDto returnDetailDto=new ReturnDetailDto();
        returnDetailDto.setBkCode(txtCode.getText());
        returnDetailDto.setQty(Integer.parseInt(txtQty.getText()));
        
        returnDetailDtos.add(returnDetailDto);
        
        Object[] rowData={returnDetailDto.getBkCode(),returnDetailDto.getQty()};
        DefaultTableModel dtm=(DefaultTableModel)tblReturn.getModel();
        dtm.addRow(rowData);
        
        clear();
    }
    
    private void clear(){
       txtCode.setText("");
       txtQty.setText("");
       lblMember.setText("");
    }
    
    private void loadTable(){
        String columns[]={"Book Code","Qty"};
        DefaultTableModel dtm =new DefaultTableModel(columns,0){
          public boolean  isCellEditable(int row,int column){
              return false;
          }  
        };
        tblReturn.setModel(dtm);
    }
    
    
    
     private void record(){
        try{
            ReturnDto returnDto=new ReturnDto();
            returnDto.setMemId(txtMemID.getText());
            returnDto.setReturnId(txtID.getText());
            
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(new Date());
            returnDto.setDate(date);          
                                        
            
            returnDto.setReturnDetailDtos(returnDetailDtos);
                       
            
            returnDto.setFine(Double.parseDouble(txtFine.getText()));
            
            String resp=returnController.record(returnDto);
            JOptionPane.showMessageDialog(this,resp);
            
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }


}
